import { Category, SareeProduct, HeroSlide, Coupon, Review } from "./types";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Kanjivaram Sarees",
    slug: "kanjivaram-sarees",
    description: "Handwoven in the ancient temple city of Kanchipuram with pure mulberry silk and authentic gold-dipped silver zari.",
    imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1600&q=80",
    itemCount: 24,
    featured: true,
  },
  {
    id: "cat-2",
    name: "Banarasi Sarees",
    slug: "banarasi-sarees",
    description: "Timeless Mughal-inspired motifs, intricate Kadwa weaves, and glorious floral jaals directly from the master weavers of Varanasi.",
    imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1600&q=80",
    itemCount: 18,
    featured: true,
  },
  {
    id: "cat-3",
    name: "Wedding Sarees",
    slug: "wedding-sarees",
    description: "Regal bridal masterpieces designed for sacred wedding vows, muhurtham moments, and grand reception ceremonies.",
    imageUrl: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1600&q=80",
    itemCount: 32,
    featured: true,
  },
  {
    id: "cat-4",
    name: "Silk Sarees",
    slug: "silk-sarees",
    description: "Pure Tussar, Mysore Crepe, Mulberry, and Raw Silk creations that drape with effortless grace and liquid lustre.",
    imageUrl: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=1600&q=80",
    itemCount: 28,
    featured: true,
  },
  {
    id: "cat-5",
    name: "Party Wear Sarees",
    slug: "party-wear-sarees",
    description: "Glamorous contemporary drapes, shimmering tissue silks, micro-sequins, and modern cocktail sarees that turn heads.",
    imageUrl: "/images/products/turquoise-tissue-1.jpg",
    bannerUrl: "/images/products/turquoise-tissue-1.jpg",
    itemCount: 20,
    featured: true,
  },
  {
    id: "cat-6",
    name: "Cotton Sarees",
    slug: "cotton-sarees",
    description: "Lightweight breathable handlooms, Mangalagiri cottons, Chanderi silks, and breathable comfort for daily luxury.",
    imageUrl: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=800&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=1600&q=80",
    itemCount: 15,
    featured: false,
  },
  {
    id: "cat-7",
    name: "Designer Sarees",
    slug: "designer-sarees",
    description: "Exclusive festive concepts, soft jacquard silks, scalloped zari borders, and artisanal limited-edition creations.",
    imageUrl: "/images/products/rani-pink-silk-1.jpg",
    bannerUrl: "/images/products/rani-pink-silk-1.jpg",
    itemCount: 16,
    featured: true,
  },
];

export const INITIAL_PRODUCTS: SareeProduct[] = [
  {
    id: "saree-01",
    sku: "RAV-KNJ-001",
    name: "Royal Crimson & Gold Temple Border Kanjivaram Silk Saree",
    slug: "royal-crimson-gold-temple-border-kanjivaram-silk",
    categoryId: "cat-1",
    categoryName: "Kanjivaram Sarees",
    description: "An authentic heirlooms piece woven with 3-ply mulberry silk, featuring an opulent solid gold zari pallu with peacock and annapakshi motifs. The body features rich crimson red tones complemented by a traditional Korvai interlocking temple border.",
    price: 4490,
    discountPrice: 2499,
    stock: 7,
    fabric: "Pure Mulberry Kanchipuram Silk",
    zariType: "Pure Gold Zari (Tested Metallic Core)",
    weaveType: "Korvai Handloom Technique",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Unstitched Brocade Silk)",
    occasion: "Bridal / Wedding",
    careInstructions: "Strictly Dry Clean Only. Store wrapped in a breathable muslin or pure cotton cover. Air out every 4 months away from direct sunlight.",
    availableColors: ["Crimson Red", "Royal Maroon", "Deep Vermillion"],
    primaryColor: "Crimson Red",
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85",
    ],
    rating: 4.9,
    reviewCount: 48,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    tags: ["Bridal", "Pure Silk", "Kanjivaram", "Gold Zari", "Handloom"],
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "saree-02",
    sku: "RAV-BAN-002",
    name: "Emerald Green & Antique Gold Kadwa Banarasi Katan Silk Saree",
    slug: "emerald-green-antique-gold-kadwa-banarasi-katan-silk",
    categoryId: "cat-2",
    categoryName: "Banarasi Sarees",
    description: "Mastercrafted in Varanasi using the laborious Kadwa hand-weaving technique, where each floral buta is individually engraved with antique gold zari without any loose threads on the reverse.",
    price: 3990,
    discountPrice: 2199,
    stock: 5,
    fabric: "Pure Katan Silk",
    zariType: "Antique Rose Gold Zari",
    weaveType: "Traditional Kadwa Handloom",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Emerald Green with Zari Border)",
    occasion: "Grand Festive",
    careInstructions: "Dry Clean Only. Protect from perfume and moisture.",
    availableColors: ["Emerald Green", "Peacock Blue", "Forest Teal"],
    primaryColor: "Emerald Green",
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=1000&q=85",
    ],
    rating: 5.0,
    reviewCount: 36,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
    tags: ["Banarasi", "Kadwa", "Emerald", "Festive", "Katan Silk"],
    createdAt: "2026-02-01T12:00:00Z",
  },
  {
    id: "saree-03",
    sku: "RAV-WED-003",
    name: "Maharani Gold Tissue Bridal Muhurtham Saree",
    slug: "maharani-gold-tissue-bridal-muhurtham-saree",
    categoryId: "cat-3",
    categoryName: "Wedding Sarees",
    description: "Fit for royalty, this full gold tissue silk saree radiates ethereal brilliance under wedding mandap lights. Decorated with intricate hand-embroidered zardozi borders and pearl beading.",
    price: 4990,
    discountPrice: 2799,
    stock: 3,
    fabric: "Pure Metallic Tissue & Mulberry Silk",
    zariType: "24K Dipped Pure Gold Zari & Micro Pearls",
    weaveType: "Brocade Tissue Jacquard",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "1.00 Meter (Heavy Embroidered Zardozi Blouse Piece)",
    occasion: "Bridal / Wedding",
    careInstructions: "Specialist Dry Clean Only. Keep in Muslin pouch.",
    availableColors: ["Royal Gold", "Champagne Bronze", "Soft Copper"],
    primaryColor: "Royal Gold",
    images: [
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85",
      "/images/products/turquoise-tissue-2.jpg",
    ],
    rating: 4.9,
    reviewCount: 29,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    tags: ["Bridal", "Maharani", "Tissue Silk", "Gold", "Luxury"],
    createdAt: "2026-01-20T14:30:00Z",
  },
  {
    id: "saree-04",
    sku: "RAV-SLK-004",
    name: "Peacock Blue Handspun Tussar Silk Saree with Kantha Stitch",
    slug: "peacock-blue-handspun-tussar-silk-kantha-stitch",
    categoryId: "cat-4",
    categoryName: "Silk Sarees",
    description: "Celebrates rural Indian artisanal craftsmanship with wild forest Tussar silk. Embellished with meticulous Bengal Kantha stitch embroidery running across the entire pallu and border.",
    price: 3290,
    discountPrice: 1849,
    stock: 9,
    fabric: "100% Pure Forest Tussar Silk",
    zariType: "Muted Antique Copper Zari",
    weaveType: "Handspun & Hand-Embroidered",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Running Tussar with Kantha Border)",
    occasion: "Reception",
    careInstructions: "Dry Clean Preferred. Mild shampoo cold wash if necessary.",
    availableColors: ["Peacock Blue", "Ochre Gold", "Rust Terracotta"],
    primaryColor: "Peacock Blue",
    images: [
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85",
    ],
    rating: 4.8,
    reviewCount: 22,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    tags: ["Tussar", "Kantha", "Silk Mark", "Handcrafted", "Heritage"],
    createdAt: "2026-02-10T09:15:00Z",
  },
  {
    id: "saree-05",
    sku: "RAV-PTY-005",
    name: "Midnight Obsidian Black Shimmer Georgette Cocktail Saree",
    slug: "midnight-obsidian-black-shimmer-georgette-cocktail-saree",
    categoryId: "cat-5",
    categoryName: "Party Wear Sarees",
    description: "Designed for high-society gala evenings and cocktail soirées. Fluid cascading French georgette illuminated with tonal micro-cut sequins that catch light with every movement.",
    price: 2990,
    discountPrice: 1699,
    stock: 12,
    fabric: "Premium Viscose Georgette with Micro-Sequins",
    zariType: "Gunmetal Tone Cutwork",
    weaveType: "Machine Embellished Precision Drape",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.85 Meters (Heavy Sequin Embroidered Velvet)",
    occasion: "Evening Party",
    careInstructions: "Dry Clean Only to protect delicate sequin finish.",
    availableColors: ["Obsidian Black", "Midnight Navy", "Deep Wine"],
    primaryColor: "Obsidian Black",
    images: [
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85",
    ],
    rating: 4.9,
    reviewCount: 54,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    tags: ["Party Wear", "Black", "Sequin", "Cocktail", "Modern"],
    createdAt: "2026-02-18T16:00:00Z",
  },
  {
    id: "saree-06",
    sku: "RAV-DSG-006",
    name: "Pastel Lavender Hand-Painted Organza Silk Saree with Scalloped Zari",
    slug: "pastel-lavender-hand-painted-organza-silk-scalloped-zari",
    categoryId: "cat-7",
    categoryName: "Designer Sarees",
    description: "Ethereal translucent pure organza silk individually painted by master botanic artists. Bordered by intricate scalloped gold threadwork and delicate french knots.",
    price: 3490,
    discountPrice: 1999,
    stock: 6,
    fabric: "Pure Translucent Organza Silk",
    zariType: "Fine Matte Gold Resham & Zari",
    weaveType: "Hand-Painted Artisanal Craft",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Raw Silk in Matching Lavender)",
    occasion: "Day Wedding / Sangeet",
    careInstructions: "Dry clean only. Do not steam press directly on artwork.",
    availableColors: ["Lavender Blush", "Mint Sage", "Powder Peach"],
    primaryColor: "Lavender Blush",
    images: [
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85",
    ],
    rating: 5.0,
    reviewCount: 19,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
    tags: ["Organza", "Hand Painted", "Pastel", "Designer", "Day Wedding"],
    createdAt: "2026-02-22T11:00:00Z",
  },
  {
    id: "saree-07",
    sku: "RAV-COT-007",
    name: "Chanderi Cotton Silk Saree with Gold Zari Bootis & Meenakari",
    slug: "chanderi-cotton-silk-gold-zari-bootis-meenakari",
    categoryId: "cat-6",
    categoryName: "Cotton Sarees",
    description: "Woven in the historic looms of Madhya Pradesh, combining the sheer lightweight comfort of fine cotton with the delicate shimmer of silk warp and dual-tone Meenakari motifs.",
    price: 2690,
    discountPrice: 1499,
    stock: 14,
    fabric: "Fine Chanderi Cotton Silk",
    zariType: "Soft Gold Tested Zari",
    weaveType: "Traditional Handloom Eknaliy",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Running Chanderi Silk)",
    occasion: "Daily Classic / Puja",
    careInstructions: "Dry Clean first two washes, thereafter gentle handwash in cold water.",
    availableColors: ["Ivory Cream", "Mustard Ochre", "Dusty Coral"],
    primaryColor: "Ivory Cream",
    images: [
      "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=1000&q=85",
    ],
    rating: 4.7,
    reviewCount: 31,
    isFeatured: false,
    isBestseller: true,
    isNewArrival: false,
    tags: ["Chanderi", "Cotton Silk", "Lightweight", "Comfort", "Handloom"],
    createdAt: "2026-01-08T08:45:00Z",
  },
  {
    id: "saree-08",
    sku: "RAV-KNJ-008",
    name: "Royal Purple & Copper Zari Brocade Kanchipuram Silk Saree",
    slug: "royal-purple-copper-zari-brocade-kanchipuram-silk",
    categoryId: "cat-1",
    categoryName: "Kanjivaram Sarees",
    description: "An aristocratic deep aubergine purple hue interwoven with rare copper zari in a Mayil (peacock) vana singaram jaal pattern. A statement of timeless South Indian royalty.",
    price: 4290,
    discountPrice: 2399,
    stock: 4,
    fabric: "Pure Mulberry Kanchipuram Silk",
    zariType: "Antique Copper Zari",
    weaveType: "Korvai Triple-Shuttle Weave",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Rich Brocade Copper Zari)",
    occasion: "Bridal / Wedding",
    careInstructions: "Dry Clean Only. Wrap in mul-mul cloth.",
    availableColors: ["Royal Purple", "Burgundy Maroon", "Deep Magenta"],
    primaryColor: "Royal Purple",
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&q=85",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1000&q=85",
    ],
    rating: 5.0,
    reviewCount: 27,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
    tags: ["Kanjivaram", "Copper Zari", "Royal Purple", "Bridal"],
    createdAt: "2026-02-25T15:20:00Z",
  },
  {
    id: "saree-09",
    sku: "RAV-TIS-009",
    name: "Turquoise Blue Tissue Silver Zariwork Saree With Matching Blouse Piece",
    slug: "turquoise-blue-tissue-silver-zariwork-saree-with-matching-blouse-piece",
    categoryId: "cat-5",
    categoryName: "Party Wear Sarees",
    description: "An enchanting turquoise blue tissue saree featuring shimmering metallic weave adorned with exquisite silver zari floral bootis and an ornate scalloped zari embroidered border. Accompanied by a coordinated matching unstitched blouse piece. Ultra-lightweight and radiant, perfect for cocktail parties, sangeet ceremonies, receptions, and celebratory festive evenings.",
    price: 2990,
    discountPrice: 1794,
    stock: 15,
    fabric: "Pure Metallic Tissue Sheer Silk Blend",
    zariType: "Intricate Silver Zari & Scalloped Resham Border",
    weaveType: "Luminescent Tissue Jacquard Weave",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Turquoise Blue with Silver Zari Border)",
    occasion: "Party Wear / Festive / Reception",
    careInstructions: "Dry Clean Only. Iron inside out on mild silk setting. Store wrapped in soft muslin cloth.",
    availableColors: ["Turquoise Blue", "Aqua Marine", "Sky Cyan"],
    primaryColor: "Turquoise Blue",
    images: [
      "/images/products/turquoise-tissue-1.jpg",
      "/images/products/turquoise-tissue-2.jpg",
      "/images/products/turquoise-tissue-3.jpg",
    ],
    rating: 4.9,
    reviewCount: 42,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    tags: ["Tissue Saree", "Silver Zari", "Turquoise Blue", "Party Wear", "Designer", "Trending", "Scallop Border"],
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "saree-10",
    sku: "RAV-SLK-010",
    name: "Rani Pink Soft Silk Saree with Rich Silver Zari Pallu & Floral Jaal",
    slug: "rani-pink-soft-silk-saree-rich-silver-zari-pallu-floral-jaal",
    categoryId: "cat-4",
    categoryName: "Silk Sarees",
    description: "A breathtaking Rani Pink soft silk saree showcasing a glorious all-over silver zari floral jaal body and a heavy contrasting zari pallu finished with handcrafted artisanal tassels. Comes with a matching unstitched blouse piece. Supremely soft, lustrous, and graceful for weddings, receptions, festivals, and celebratory occasions.",
    price: 3490,
    discountPrice: 1949,
    stock: 12,
    fabric: "Pure Litchi Soft Silk",
    zariType: "Intricate Silver & Light Gold Dual Zari Weave",
    weaveType: "Jacquard Floral Jaal with Tassel Pallu",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Matching Rani Pink Brocade Silk)",
    occasion: "Wedding / Grand Festive / Reception",
    careInstructions: "Dry Clean Only. Wrap in mul-mul cloth. Iron on reverse side on low silk heat.",
    availableColors: ["Rani Pink", "Ruby Rose", "Magenta"],
    primaryColor: "Rani Pink",
    images: [
      "/images/products/rani-pink-silk-1.jpg",
      "/images/products/rani-pink-silk-2.jpg",
      "/images/products/rani-pink-silk-3.jpg",
      "/images/products/rani-pink-silk-4.jpg",
      "/images/products/rani-pink-silk-5.jpg",
    ],
    rating: 5.0,
    reviewCount: 38,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    tags: ["Rani Pink", "Soft Silk", "Zari Pallu", "Tassels", "Wedding Saree", "Banarasi", "Trending"],
    createdAt: "2026-03-08T10:00:00Z",
  },
];

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: "hero-1",
    tagline: "The Festive & Wedding Edit 2026",
    title: "Tradition · Grace · For Every You",
    subtitle: "Handcrafted pure zari sarees, Banarasi masterlooms, and heirloom bridal silks starting at ₹1,499.",
    accentText: "Accessible Luxury · 100% Pure Silk Mark",
    imageUrl: "/images/hero/hero-banner-1.png",
    linkUrl: "/shop",
    buttonText: "Explore Collection",
  },
  {
    id: "hero-2",
    tagline: "Festive Loom Heritage",
    title: "Happy Onam · Sarees That Celebrate Our Roots",
    subtitle: "Pure Kerala Kasavu weaves, golden temple borders, and festive handloom drapes for sacred celebrations.",
    accentText: "Complimentary Express Pan-India Delivery",
    imageUrl: "/images/hero/hero-banner-2.png",
    linkUrl: "/category/cotton-sarees",
    buttonText: "Shop Onam Collection",
  },
  {
    id: "hero-3",
    tagline: "Sarees For Every You",
    title: "Tradition in Every Drape",
    subtitle: "Soft shimmering tissue drapes, intricate floral jaals, and bespoke designer sarees starting at ₹1,794.",
    accentText: "40% to 44% Introductory Discounts",
    imageUrl: "/images/hero/hero-banner-3.png",
    linkUrl: "/product/turquoise-blue-tissue-silver-zariwork-saree-with-matching-blouse-piece",
    buttonText: "Discover Shimmer Sarees",
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "coup-1",
    code: "RAVINA10",
    discountType: "percentage",
    discountValue: 10,
    minOrderValue: 2500,
    maxDiscount: 500,
    description: "10% off on all sarees for orders above ₹2,500",
    isActive: true,
    expiresAt: "2026-12-31T23:59:59Z",
  },
  {
    id: "coup-2",
    code: "ROYAL400",
    discountType: "fixed",
    discountValue: 400,
    minOrderValue: 3500,
    description: "Flat ₹400 instant savings on orders above ₹3,500",
    isActive: true,
    expiresAt: "2026-12-31T23:59:59Z",
  },
  {
    id: "coup-3",
    code: "FIRSTBUY",
    discountType: "percentage",
    discountValue: 15,
    minOrderValue: 1500,
    maxDiscount: 350,
    description: "15% off for your first royal saree order at Ravina Sarees",
    isActive: true,
    expiresAt: "2026-12-31T23:59:59Z",
  },
  {
    id: "coup-4",
    code: "FESTIVE200",
    discountType: "fixed",
    discountValue: 200,
    minOrderValue: 2000,
    description: "Flat ₹200 off on festive handloom collection above ₹2,000",
    isActive: true,
    expiresAt: "2026-12-31T23:59:59Z",
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    productId: "saree-01",
    userName: "Ananya Reddy",
    userCity: "Hyderabad",
    rating: 5,
    title: "Mesmerizing bridal saree, pure heirloom quality!",
    comment: "I purchased this Kanjivaram for my wedding muhurtham in Hyderabad. The zari shine is rich without being gaudy, and the silk weight feels remarkably opulent. Everyone at the mandap asked about Ravina Sarees!",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-02-12T14:20:00Z",
    likes: 24,
  },
  {
    id: "rev-2",
    productId: "saree-02",
    userName: "Deepika Rao",
    userCity: "Bangalore",
    rating: 5,
    title: "Genuine Kadwa Banarasi with zero loose threads",
    comment: "As a handloom enthusiast, I was amazed by the perfection of the Kadwa weave. Shipped within 48 hours to Bangalore in a gorgeous gold luxury box. Truly exceptional customer service.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-02-18T09:40:00Z",
    likes: 18,
  },
  {
    id: "rev-3",
    productId: "saree-03",
    userName: "Dr. Shalini Varma",
    userCity: "Chennai",
    rating: 5,
    title: "Felt like a queen on my reception day",
    comment: "The gold tissue drape catches the light in the most flattering way. Comes with Silk Mark tag and authenticated zari certificate. Will cherish this for decades.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-02-24T16:15:00Z",
    likes: 15,
  },
  {
    id: "rev-4",
    productId: "saree-09",
    userName: "Meghana Deshmukh",
    userCity: "Pune",
    rating: 5,
    title: "Mesmerizing turquoise shade and dazzling silver zari!",
    comment: "The tissue fabric is so light and shimmering! The silver zari embroidery and scalloped border look ten times more expensive than ₹1,794. Wore it to my best friend's reception and received endless compliments!",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-02T11:30:00Z",
    likes: 31,
  },
  {
    id: "rev-5",
    productId: "saree-09",
    userName: "Sanjana Roy",
    userCity: "Hyderabad",
    rating: 5,
    title: "Unbelievable value at 40% discount!",
    comment: "Received the saree in 24 hours in Hyderabad. The matching blouse piece is high quality and the shine under chandelier lights is breathtaking.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-05T14:15:00Z",
    likes: 19,
  },
  {
    id: "rev-6",
    productId: "saree-10",
    userName: "Pooja Hegde",
    userCity: "Hyderabad",
    rating: 5,
    title: "The Rani Pink color & silver zari pallu are exquisite!",
    comment: "The soft litchi silk drapes like butter! The tassel details on the pallu are so well-finished. Absolute value for money at ₹1,949. Packed beautifully in a luxury box.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-08T15:00:00Z",
    likes: 27,
  },
  {
    id: "rev-7",
    productId: "saree-10",
    userName: "Nandini Sharma",
    userCity: "Mumbai",
    rating: 5,
    title: "Stunning festive saree, received so many compliments",
    comment: "Wore this for a family wedding sangeet. The contrast blouse and silver zari work looks extremely royal. Delivered in just 2 days to Mumbai.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-09T12:30:00Z",
    likes: 14,
  },
];

export const TESTIMONIALS = [
  {
    id: "test-1",
    name: "Lakshmi Narayanan",
    role: "Bride & Classical Dancer",
    city: "Hyderabad",
    rating: 5,
    quote: "Ravina Sarees understands the soul of South Indian handlooms. The fall, the zari lustre, and the sheer elegance of their Kanchipuram silks are unmatched in Telangana.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
  },
  {
    id: "test-2",
    name: "Sunita Deshmukh",
    role: "Art Collector & Curator",
    city: "Mumbai",
    rating: 5,
    quote: "Ordering sarees online was daunting until I found Ravina. The packaging, certified silk authenticity, and quick BlueDart delivery made it a five-star luxury boutique experience.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
  },
  {
    id: "test-3",
    name: "Pooja Singhania",
    role: "Fashion Stylist",
    city: "Delhi NCR",
    rating: 5,
    quote: "The intricate Kadwa Banarasi and soft jacquard tissue sarees from Ravina have become my top recommendation for bridal styling across North and South weddings.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
  },
];
