import { Category, SareeProduct, HeroSlide, Coupon, Review } from "./types";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-5",
    name: "Party Wear Sarees",
    slug: "party-wear-sarees",
    description: "Glamorous contemporary drapes, shimmering tissue silks, sheer organzas, and modern cocktail sarees that turn heads.",
    imageUrl: "/images/products/lavender-organza-1.jpg",
    bannerUrl: "/images/products/lavender-organza-1.jpg",
    itemCount: 2,
    featured: true,
  },
  {
    id: "cat-4",
    name: "Silk Sarees",
    slug: "silk-sarees",
    description: "Pure Kanjivaram, Mulberry, and soft Litchi Silk creations that drape with effortless grace and liquid lustre.",
    imageUrl: "/images/products/emerald-kanjivaram-1.jpg",
    bannerUrl: "/images/products/emerald-kanjivaram-1.jpg",
    itemCount: 2,
    featured: true,
  },
  {
    id: "cat-7",
    name: "Designer Sarees",
    slug: "designer-sarees",
    description: "Exclusive festive concepts, midnight jacquards, scalloped zari borders, and artisanal limited-edition creations.",
    imageUrl: "/images/products/navy-designer-1.jpg",
    bannerUrl: "/images/products/navy-designer-1.jpg",
    itemCount: 1,
    featured: true,
  },
  {
    id: "cat-3",
    name: "Wedding Sarees",
    slug: "wedding-sarees",
    description: "Regal bridal masterpieces designed for sacred wedding vows, muhurtham moments, and grand reception ceremonies.",
    imageUrl: "/images/products/golden-kanchipuram-1.jpg",
    bannerUrl: "/images/products/golden-kanchipuram-1.jpg",
    itemCount: 2,
    featured: true,
  },
  {
    id: "cat-2",
    name: "Banarasi Heritage",
    slug: "banarasi-sarees",
    description: "Authentic Varanasi Kadhwa brocades, son-rupa gold and silver motifs, and royal court-inspired heirloom masterworks.",
    imageUrl: "/images/products/maroon-banarasi-1.jpg",
    bannerUrl: "/images/products/maroon-banarasi-1.jpg",
    itemCount: 2,
    featured: true,
  },
  {
    id: "cat-1",
    name: "Handloom Silks",
    slug: "handloom-sarees",
    description: "Traditional masterloom craftsmanship, certified Silk Mark drapes, temple Korvai borders, and generational bridal weaves.",
    imageUrl: "/images/products/rani-pink-silk-1.jpg",
    bannerUrl: "/images/products/rani-pink-silk-1.jpg",
    itemCount: 3,
    featured: true,
  },
];

export const INITIAL_PRODUCTS: SareeProduct[] = [
  {
    id: "saree-09",
    sku: "RAV-TIS-009",
    name: "Turquoise Blue Tissue Silver Zariwork Saree With Matching Blouse Piece",
    slug: "turquoise-blue-tissue-silver-zariwork-saree-with-matching-blouse-piece",
    categoryId: "cat-5",
    categoryName: "Party Wear Sarees",
    description: "An enchanting turquoise blue tissue saree featuring shimmering metallic weave adorned with exquisite silver zari floral bootis and an ornate scalloped zari embroidered border. Accompanied by a coordinated matching unstitched blouse piece. Ultra-lightweight and radiant, perfect for cocktail parties, sangeet ceremonies, receptions, and celebratory festive evenings.",
    price: 2990,
    discountPrice: 1794,
    stock: 15,
    fabric: "Pure Metallic Tissue Sheer Silk Blend",
    zariType: "Intricate Silver Zari & Scalloped Resham Border",
    weaveType: "Luminescent Tissue Jacquard Weave",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Turquoise Blue with Silver Zari Border)",
    occasion: "Party Wear / Festive / Reception",
    careInstructions: "Dry Clean Only. Iron inside out on mild silk setting. Store wrapped in soft muslin cloth.",
    availableColors: ["Turquoise Blue", "Aqua Marine", "Sky Cyan"],
    primaryColor: "Turquoise Blue",
    images: [
      "/images/products/turquoise-tissue-1.jpg",
      "/images/products/turquoise-tissue-2.jpg",
      "/images/products/turquoise-tissue-3.jpg",
    ],
    rating: 4.9,
    reviewCount: 42,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    tags: ["Tissue Saree", "Silver Zari", "Turquoise Blue", "Party Wear", "Designer", "Trending", "Scallop Border"],
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "saree-10",
    sku: "RAV-SLK-010",
    name: "Rani Pink Soft Silk Saree with Rich Silver Zari Pallu & Floral Jaal",
    slug: "rani-pink-soft-silk-saree-rich-silver-zari-pallu-floral-jaal",
    categoryId: "cat-4",
    categoryName: "Silk Sarees",
    description: "A breathtaking Rani Pink soft silk saree showcasing a glorious all-over silver zari floral jaal body and a heavy contrasting zari pallu finished with handcrafted artisanal tassels. Comes with a matching unstitched blouse piece. Supremely soft, lustrous, and graceful for weddings, receptions, festivals, and celebratory occasions.",
    price: 3490,
    discountPrice: 1949,
    stock: 12,
    fabric: "Pure Litchi Soft Silk",
    zariType: "Intricate Silver & Light Gold Dual Zari Weave",
    weaveType: "Jacquard Floral Jaal with Tassel Pallu",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Matching Rani Pink Brocade Silk)",
    occasion: "Wedding / Grand Festive / Reception",
    careInstructions: "Dry Clean Only. Wrap in mul-mul cloth. Iron on reverse side on low silk heat.",
    availableColors: ["Rani Pink", "Ruby Rose", "Magenta"],
    primaryColor: "Rani Pink",
    images: [
      "/images/products/rani-pink-silk-1.jpg",
      "/images/products/rani-pink-silk-2.jpg",
      "/images/products/rani-pink-silk-3.jpg",
      "/images/products/rani-pink-silk-4.jpg",
      "/images/products/rani-pink-silk-5.jpg",
    ],
    rating: 5.0,
    reviewCount: 38,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    tags: ["Rani Pink", "Soft Silk", "Zari Pallu", "Tassels", "Wedding Saree", "Banarasi", "Trending"],
    createdAt: "2026-03-08T10:00:00Z",
  },
  {
    id: "saree-11",
    sku: "RAV-KAN-011",
    name: "Emerald Green Royal Kanjivaram Silk Saree with Temple Border & Pure Zari Pallu",
    slug: "emerald-green-royal-kanjivaram-silk-saree-temple-border-zari-pallu",
    categoryId: "cat-4",
    categoryName: "Silk Sarees",
    description: "An awe-inspiring Emerald Green Kanjivaram silk masterpiece woven with majestic peacock and floral motifs across a rich lustrous field. Framed by an ornate ruby crimson temple korvai border and a sumptuous pure gold zari brocade pallu. Accompanied by a designer unstitched contrast crimson blouse piece. Perfect for muhurthams, family pujas, and regal evening galas.",
    price: 4290,
    discountPrice: 2490,
    stock: 10,
    fabric: "Pure Mulberry Kanchipuram Soft Silk",
    zariType: "Pure Gold & Antique Copper Dual Tone Zari",
    weaveType: "Handcrafted Korvai Temple Jacquard Weave",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Crimson Red with Heavy Gold Zari Border)",
    occasion: "Wedding / Temple Puja / Reception",
    careInstructions: "Dry clean only. Preserve in soft breathable muslin cloth bag. Avoid direct perfume spray.",
    availableColors: ["Emerald Green", "Peacock Green", "Deep Forest Green"],
    primaryColor: "Emerald Green",
    images: [
      "/images/products/emerald-kanjivaram-1.jpg",
    ],
    rating: 4.95,
    reviewCount: 34,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    tags: ["Kanjivaram", "Silk Saree", "Emerald Green", "Temple Border", "Gold Zari", "Handloom", "Bridal"],
    createdAt: "2026-03-12T10:00:00Z",
  },
  {
    id: "saree-12",
    sku: "RAV-BAN-012",
    name: "Royal Maroon Banarasi Brocade Bridal Saree with Kadhwa Floral Weave",
    slug: "royal-maroon-banarasi-brocade-bridal-saree-kadhwa-floral-weave",
    categoryId: "cat-3",
    categoryName: "Wedding Sarees",
    description: "A timeless heritage bridal masterpiece in deep Royal Maroon katan silk, lavishly woven using age-old Banarasi Kadhwa craftsmanship. Embellished with resplendent son-rupa (gold and silver) zari floral jaal and a dense regal paithani-inspired border. Features an intricately woven ceremonial aanchal (pallu). Includes a matching brocade blouse piece.",
    price: 4890,
    discountPrice: 2899,
    stock: 8,
    fabric: "Pure Katan Silk Banarasi Brocade",
    zariType: "Heritage Son-Rupa (Dual Gold & Silver) Tested Zari",
    weaveType: "Authentic Banarasi Hand-Woven Kadhwa Jaal",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.85 Meters (Deep Maroon Brocade with Zari Sleeves)",
    occasion: "Bridal Muhurtham / Grand Wedding / Sangeet",
    careInstructions: "Strictly Dry Clean. Air out periodically in shaded breeze. Wrap in acid-free mul-mul.",
    availableColors: ["Royal Maroon", "Vermilion Red", "Crimson Wine"],
    primaryColor: "Royal Maroon",
    images: [
      "/images/products/maroon-banarasi-1.jpg",
    ],
    rating: 5.0,
    reviewCount: 52,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: false,
    tags: ["Banarasi", "Bridal", "Royal Maroon", "Kadhwa", "Wedding Saree", "Heirloom", "Brocade"],
    createdAt: "2026-03-14T10:00:00Z",
  },
  {
    id: "saree-13",
    sku: "RAV-DSG-013",
    name: "Midnight Navy Blue Designer Paisley Silk Saree with Rose Gold Embellishments",
    slug: "midnight-navy-blue-designer-paisley-silk-saree-rose-gold",
    categoryId: "cat-7",
    categoryName: "Designer Sarees",
    description: "Contemporary opulence meets timeless Indian heritage in this Midnight Navy Blue designer silk saree. Adorned with delicate stylized paisley (kalakaar) motifs rendered in subtle rose gold zari and fine micro-cutdana bead accents along the scalloped borders. Drapes with fluid elegance and modern drama for sophisticated cocktail soirees and high-fashion galas.",
    price: 3890,
    discountPrice: 2249,
    stock: 14,
    fabric: "Rich Satin Crepe & Raw Silk Jacquard",
    zariType: "Modern Rose Gold & Metallic Copper Sheen Zari",
    weaveType: "Intricate Paisley Jacquard with Hand-Finished Scallop",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Midnight Navy Embroidered Designer Blouse)",
    occasion: "Cocktail Party / Reception / Festive Soiree",
    careInstructions: "Dry Clean Recommended. Do not brush beads. Press with warm iron on reverse.",
    availableColors: ["Midnight Navy", "Royal Indigo", "Sapphire Blue"],
    primaryColor: "Navy Blue",
    images: [
      "/images/products/navy-designer-1.jpg",
    ],
    rating: 4.88,
    reviewCount: 29,
    isFeatured: true,
    isBestseller: false,
    isNewArrival: true,
    tags: ["Designer Saree", "Navy Blue", "Rose Gold", "Paisley", "Cocktail", "Party Wear", "Satin Crepe"],
    createdAt: "2026-03-18T10:00:00Z",
  },
  {
    id: "saree-14",
    sku: "RAV-ORG-014",
    name: "Ethereal Lavender Sheer Organza Silk Saree with Floral Silver Zari Border",
    slug: "ethereal-lavender-sheer-organza-silk-saree-silver-zari-border",
    categoryId: "cat-5",
    categoryName: "Party Wear Sarees",
    description: "Delicate, dreamy, and utterly poetic — this gossamer Lavender Organza silk saree floats effortlessly around you. Features ethereal silver zari blooming vines and lustrous scalloped embroidery along all four borders. Paired with a tone-on-tone lustrous raw silk blouse piece. A celebrity-favorite drape for daytime engagements, mehendi festivities, and summer soirees.",
    price: 3190,
    discountPrice: 1849,
    stock: 18,
    fabric: "Pure Sheer Crystal Organza Silk",
    zariType: "Shimmering Silver Metallic Thread & Resham Embroidery",
    weaveType: "Lightweight Sheer Organza with Scalloped Zari Edge",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.80 Meters (Lavender Raw Silk Unstitched Fabric)",
    occasion: "Daytime Wedding / Engagement / Mehendi / Cocktail",
    careInstructions: "Gentle Dry Clean Only. Avoid wringing. Store flat or hung on padded hangers.",
    availableColors: ["Ethereal Lavender", "Lilac Mist", "Pastel Violet"],
    primaryColor: "Lavender",
    images: [
      "/images/products/lavender-organza-1.jpg",
    ],
    rating: 4.92,
    reviewCount: 26,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    tags: ["Organza Silk", "Lavender", "Pastel Saree", "Party Wear", "Floral Border", "Trending", "Lightweight"],
    createdAt: "2026-03-20T10:00:00Z",
  },
  {
    id: "saree-15",
    sku: "RAV-KAN-015",
    name: "Swarna Golden Bridal Kanchipuram Silk Saree with Crimson Red Temple Pallu",
    slug: "swarna-golden-bridal-kanchipuram-silk-saree-crimson-temple-pallu",
    categoryId: "cat-3",
    categoryName: "Wedding Sarees",
    description: "The quintessential South Indian bridal heirloom. Woven in brilliant mustard Swarna gold pure silk with an opulent crimson red pallu showcasing Goddess Lakshmi motifs, sacred rudraksha patterns, and royal chariots. Heavy authentic gold zari brocade that drapes with regal majesty for sacred pheras, thali ceremonies, and heirloom bridal collections.",
    price: 5290,
    discountPrice: 3199,
    stock: 7,
    fabric: "Pure Kanchipuram Heavy Bridal Mulberry Silk",
    zariType: "Pure 2G Gold Tested Zari with Heavy Red Pallu Brocade",
    weaveType: "Masterloom Korvai 3-Shuttle Traditional Weave",
    sareeLength: "5.5 Meters",
    blouseIncluded: true,
    blouseLength: "0.85 Meters (Deep Crimson Red Brocade with Heavy Zari Sleeve Border)",
    occasion: "Muhurtham / Bridal Pheras / Grand Reception",
    careInstructions: "Dry Clean Only. Never spray water or perfumes directly. Air in shade twice yearly.",
    availableColors: ["Swarna Golden Mustard", "Antique Honey Gold", "Haldi Yellow"],
    primaryColor: "Golden Mustard",
    images: [
      "/images/products/golden-kanchipuram-1.jpg",
    ],
    rating: 5.0,
    reviewCount: 47,
    isFeatured: true,
    isBestseller: true,
    isNewArrival: true,
    tags: ["Bridal Saree", "Golden Saree", "Kanchipuram", "Pure Silk", "Muhurtham", "Temple Pallu", "Heirloom"],
    createdAt: "2026-03-22T10:00:00Z",
  },
];

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: "hero-1",
    tagline: "The Festive & Wedding Edit 2026",
    title: "Tradition · Grace · For Every You",
    subtitle: "Handcrafted pure zari sarees, Banarasi masterlooms, and heirloom bridal silks starting at ₹1,794.",
    accentText: "Accessible Luxury · 100% Pure Silk Mark",
    imageUrl: "/images/hero/hero-banner-1.png",
    linkUrl: "/shop",
    buttonText: "Explore Collection",
  },
  {
    id: "hero-2",
    tagline: "Festive Loom Heritage",
    title: "Happy Onam · Sarees That Celebrate Our Roots",
    subtitle: "Pure South Indian weaves, golden temple borders, and festive handloom drapes for sacred celebrations.",
    accentText: "Complimentary Express Pan-India Delivery",
    imageUrl: "/images/hero/hero-banner-2.png",
    linkUrl: "/shop",
    buttonText: "Shop Festive Collection",
  },
  {
    id: "hero-3",
    tagline: "Sarees For Every You",
    title: "Tradition in Every Drape",
    subtitle: "Soft shimmering tissue drapes, intricate floral jaals, and bespoke designer sarees starting at ₹1,794.",
    accentText: "40% to 44% Introductory Discounts",
    imageUrl: "/images/hero/hero-banner-3.png",
    linkUrl: "/product/turquoise-blue-tissue-silver-zariwork-saree-with-matching-blouse-piece",
    buttonText: "Discover Shimmer Sarees",
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "coup-1",
    code: "RAVINA10",
    discountType: "percentage",
    discountValue: 10,
    minOrderValue: 2500,
    maxDiscount: 500,
    description: "10% off on all sarees for orders above ₹2,500",
    isActive: true,
    expiresAt: "2026-12-31T23:59:59Z",
  },
  {
    id: "coup-2",
    code: "ROYAL400",
    discountType: "fixed",
    discountValue: 400,
    minOrderValue: 3500,
    description: "Flat ₹400 instant savings on orders above ₹3,500",
    isActive: true,
    expiresAt: "2026-12-31T23:59:59Z",
  },
  {
    id: "coup-3",
    code: "FIRSTBUY",
    discountType: "percentage",
    discountValue: 15,
    minOrderValue: 1500,
    maxDiscount: 350,
    description: "15% off for your first royal saree order at Ravina Sarees",
    isActive: true,
    expiresAt: "2026-12-31T23:59:59Z",
  },
  {
    id: "coup-4",
    code: "FESTIVE200",
    discountType: "fixed",
    discountValue: 200,
    minOrderValue: 2000,
    description: "Flat ₹200 off on festive handloom collection above ₹2,000",
    isActive: true,
    expiresAt: "2026-12-31T23:59:59Z",
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-4",
    productId: "saree-09",
    userName: "Meghana Deshmukh",
    userCity: "Pune",
    rating: 5,
    title: "Mesmerizing turquoise shade and dazzling silver zari!",
    comment: "The tissue fabric is so light and shimmering! The silver zari embroidery and scalloped border look ten times more expensive than ₹1,794. Wore it to my best friend's reception and received endless compliments!",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-02T11:30:00Z",
    likes: 31,
  },
  {
    id: "rev-5",
    productId: "saree-09",
    userName: "Sanjana Roy",
    userCity: "Hyderabad",
    rating: 5,
    title: "Unbelievable value at 40% discount!",
    comment: "Received the saree in 24 hours in Hyderabad. The matching blouse piece is high quality and the shine under chandelier lights is breathtaking.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-05T14:15:00Z",
    likes: 19,
  },
  {
    id: "rev-6",
    productId: "saree-10",
    userName: "Pooja Hegde",
    userCity: "Hyderabad",
    rating: 5,
    title: "The Rani Pink color & silver zari pallu are exquisite!",
    comment: "The soft litchi silk drapes like butter! The tassel details on the pallu are so well-finished. Absolute value for money at ₹1,949. Packed beautifully in a luxury box.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-08T15:00:00Z",
    likes: 27,
  },
  {
    id: "rev-7",
    productId: "saree-10",
    userName: "Nandini Sharma",
    userCity: "Mumbai",
    rating: 5,
    title: "Stunning festive saree, received so many compliments",
    comment: "Wore this for a family wedding sangeet. The contrast blouse and silver zari work looks extremely royal. Delivered in just 2 days to Mumbai.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-09T12:30:00Z",
    likes: 14,
  },
  {
    id: "rev-8",
    productId: "saree-11",
    userName: "Kavitha Raghunath",
    userCity: "Bengaluru",
    rating: 5,
    title: "Temple border and emerald tone look pure regal!",
    comment: "The dual tone gold zari and rich contrast crimson border are magnificent. The drape stays perfectly structured throughout the ceremony without feeling heavy. Ravina Sarees has won a customer for life!",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-15T10:20:00Z",
    likes: 22,
  },
  {
    id: "rev-9",
    productId: "saree-12",
    userName: "Sunita Agarwal",
    userCity: "Varanasi",
    rating: 5,
    title: "Authentic Banarasi Kadhwa feel at an unbeatable price",
    comment: "Coming from Varanasi, I know fine handlooms. The son-rupa dual zari and dense floral jaal work on this maroon saree are heirloom quality. Arrived in immaculate packaging with certification.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-17T16:45:00Z",
    likes: 38,
  },
  {
    id: "rev-10",
    productId: "saree-13",
    userName: "Aarti Mehra",
    userCity: "Delhi",
    rating: 5,
    title: "The rose gold zari against midnight navy is breathtaking",
    comment: "Modern, chic, and completely unique. Wore this to an evening cocktail reception and turned heads all night. Fabric has a delicate shimmer and doesn't crease.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-19T13:10:00Z",
    likes: 17,
  },
  {
    id: "rev-11",
    productId: "saree-14",
    userName: "Deepika Rao",
    userCity: "Chennai",
    rating: 5,
    title: "Cloud-light organza and fairy-tale lavender shade",
    comment: "I was worried organza might puff up, but this crystal silk blend falls so softly! The silver scalloped border is delicately embroidered. Perfect for daytime occasions.",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-21T09:40:00Z",
    likes: 24,
  },
  {
    id: "rev-12",
    productId: "saree-15",
    userName: "Shravya Reddy",
    userCity: "Warangal",
    rating: 5,
    title: "Masterpiece wedding saree! Felt like a royal bride",
    comment: "The Swarna gold lustre and deep crimson red temple pallu with chariot motifs are pure artistry. We used this for our family muhurtham and everyone asked where we bought it!",
    verifiedPurchase: true,
    status: "approved",
    createdAt: "2026-03-23T18:05:00Z",
    likes: 41,
  },
];

export const TESTIMONIALS = [
  {
    id: "test-1",
    name: "Lakshmi Narayanan",
    role: "Bride & Classical Dancer",
    city: "Hyderabad",
    rating: 5,
    quote: "Ravina Sarees understands the soul of South Indian handlooms. The fall, the zari lustre, and the sheer elegance of their silks are unmatched in Telangana.",
    image: "/images/products/golden-kanchipuram-1.jpg",
  },
  {
    id: "test-2",
    name: "Sunita Deshmukh",
    role: "Art Collector & Curator",
    city: "Mumbai",
    rating: 5,
    quote: "Ordering sarees online was daunting until I found Ravina. The packaging, certified silk authenticity, and quick BlueDart delivery made it a five-star luxury boutique experience.",
    image: "/images/products/maroon-banarasi-1.jpg",
  },
  {
    id: "test-3",
    name: "Pooja Singhania",
    role: "Fashion Stylist",
    city: "Delhi NCR",
    rating: 5,
    quote: "The intricate zari tissue and soft jacquard silk sarees from Ravina have become my top recommendation for bridal styling across North and South weddings.",
    image: "/images/products/lavender-organza-1.jpg",
  },
];
